"""Auto-generated ISO lookup for primary-dataset country names.
Maps gapminder country name -> (ISO 3166-1 alpha-3, ISO 3166-1 numeric).
Numeric codes match the world-atlas TopoJSON feature ids used by the choropleth (V4).
Generated once via pycountry; embedded so the pipeline has no runtime pycountry dependency.
"""

ISO_MAP = {
    'Albania': ('ALB', '008'),
    'Algeria': ('DZA', '012'),
    'Angola': ('AGO', '024'),
    'Antigua and Barbuda': ('ATG', '028'),
    'Argentina': ('ARG', '032'),
    'Armenia': ('ARM', '051'),
    'Aruba': ('ABW', '533'),
    'Australia': ('AUS', '036'),
    'Austria': ('AUT', '040'),
    'Azerbaijan': ('AZE', '031'),
    'Bahamas': ('BHS', '044'),
    'Bahrain': ('BHR', '048'),
    'Bangladesh': ('BGD', '050'),
    'Barbados': ('BRB', '052'),
    'Belarus': ('BLR', '112'),
    'Belgium': ('BEL', '056'),
    'Belize': ('BLZ', '084'),
    'Benin': ('BEN', '204'),
    'Bhutan': ('BTN', '064'),
    'Bolivia': ('BOL', '068'),
    'Bosnia and Herzegovina': ('BIH', '070'),
    'Botswana': ('BWA', '072'),
    'Brazil': ('BRA', '076'),
    'Brunei': ('BRN', '096'),
    'Bulgaria': ('BGR', '100'),
    'Burkina Faso': ('BFA', '854'),
    'Burundi': ('BDI', '108'),
    'Cambodia': ('KHM', '116'),
    'Cameroon': ('CMR', '120'),
    'Canada': ('CAN', '124'),
    'Cape Verde': ('CPV', '132'),
    'Central African Republic': ('CAF', '140'),
    'Chad': ('TCD', '148'),
    'Chile': ('CHL', '152'),
    'China': ('CHN', '156'),
    'Colombia': ('COL', '170'),
    'Comoros': ('COM', '174'),
    'Congo, Dem. Rep.': ('COD', '180'),
    'Congo, Rep.': ('COG', '178'),
    'Costa Rica': ('CRI', '188'),
    "Cote d'Ivoire": ('CIV', '384'),
    'Croatia': ('HRV', '191'),
    'Cuba': ('CUB', '192'),
    'Cyprus': ('CYP', '196'),
    'Czech Republic': ('CZE', '203'),
    'Denmark': ('DNK', '208'),
    'Djibouti': ('DJI', '262'),
    'Dominican Republic': ('DOM', '214'),
    'Ecuador': ('ECU', '218'),
    'Egypt': ('EGY', '818'),
    'El Salvador': ('SLV', '222'),
    'Equatorial Guinea': ('GNQ', '226'),
    'Eritrea': ('ERI', '232'),
    'Estonia': ('EST', '233'),
    'Ethiopia': ('ETH', '231'),
    'Fiji': ('FJI', '242'),
    'Finland': ('FIN', '246'),
    'France': ('FRA', '250'),
    'French Polynesia': ('PYF', '258'),
    'Gabon': ('GAB', '266'),
    'Gambia': ('GMB', '270'),
    'Georgia': ('GEO', '268'),
    'Germany': ('DEU', '276'),
    'Ghana': ('GHA', '288'),
    'Greece': ('GRC', '300'),
    'Greenland': ('GRL', '304'),
    'Grenada': ('GRD', '308'),
    'Guatemala': ('GTM', '320'),
    'Guinea': ('GIN', '324'),
    'Guinea-Bissau': ('GNB', '624'),
    'Guyana': ('GUY', '328'),
    'Haiti': ('HTI', '332'),
    'Honduras': ('HND', '340'),
    'Hong Kong, China': ('HKG', '344'),
    'Hungary': ('HUN', '348'),
    'Iceland': ('ISL', '352'),
    'India': ('IND', '356'),
    'Indonesia': ('IDN', '360'),
    'Iran': ('IRN', '364'),
    'Iraq': ('IRQ', '368'),
    'Ireland': ('IRL', '372'),
    'Israel': ('ISR', '376'),
    'Italy': ('ITA', '380'),
    'Jamaica': ('JAM', '388'),
    'Japan': ('JPN', '392'),
    'Jordan': ('JOR', '400'),
    'Kazakhstan': ('KAZ', '398'),
    'Kenya': ('KEN', '404'),
    'Kiribati': ('KIR', '296'),
    'Kuwait': ('KWT', '414'),
    'Kyrgyz Republic': ('KGZ', '417'),
    'Lao': ('LAO', '418'),
    'Latvia': ('LVA', '428'),
    'Lebanon': ('LBN', '422'),
    'Lesotho': ('LSO', '426'),
    'Liberia': ('LBR', '430'),
    'Libya': ('LBY', '434'),
    'Lithuania': ('LTU', '440'),
    'Luxembourg': ('LUX', '442'),
    'Macao, China': ('MAC', '446'),
    'Macedonia, FYR': ('MKD', '807'),
    'Madagascar': ('MDG', '450'),
    'Malawi': ('MWI', '454'),
    'Malaysia': ('MYS', '458'),
    'Maldives': ('MDV', '462'),
    'Mali': ('MLI', '466'),
    'Malta': ('MLT', '470'),
    'Mauritania': ('MRT', '478'),
    'Mauritius': ('MUS', '480'),
    'Mexico': ('MEX', '484'),
    'Micronesia, Fed. Sts.': ('FSM', '583'),
    'Moldova': ('MDA', '498'),
    'Mongolia': ('MNG', '496'),
    'Montenegro': ('MNE', '499'),
    'Morocco': ('MAR', '504'),
    'Mozambique': ('MOZ', '508'),
    'Namibia': ('NAM', '516'),
    'Nepal': ('NPL', '524'),
    'Netherlands': ('NLD', '528'),
    'New Caledonia': ('NCL', '540'),
    'New Zealand': ('NZL', '554'),
    'Nicaragua': ('NIC', '558'),
    'Niger': ('NER', '562'),
    'Nigeria': ('NGA', '566'),
    'Norway': ('NOR', '578'),
    'Oman': ('OMN', '512'),
    'Pakistan': ('PAK', '586'),
    'Panama': ('PAN', '591'),
    'Papua New Guinea': ('PNG', '598'),
    'Paraguay': ('PRY', '600'),
    'Peru': ('PER', '604'),
    'Philippines': ('PHL', '608'),
    'Poland': ('POL', '616'),
    'Portugal': ('PRT', '620'),
    'Puerto Rico': ('PRI', '630'),
    'Qatar': ('QAT', '634'),
    'Romania': ('ROU', '642'),
    'Russia': ('RUS', '643'),
    'Rwanda': ('RWA', '646'),
    'Samoa': ('WSM', '882'),
    'Saudi Arabia': ('SAU', '682'),
    'Senegal': ('SEN', '686'),
    'Serbia': ('SRB', '688'),
    'Seychelles': ('SYC', '690'),
    'Sierra Leone': ('SLE', '694'),
    'Singapore': ('SGP', '702'),
    'Slovak Republic': ('SVK', '703'),
    'Slovenia': ('SVN', '705'),
    'Solomon Islands': ('SLB', '090'),
    'South Africa': ('ZAF', '710'),
    'South Korea': ('KOR', '410'),
    'Spain': ('ESP', '724'),
    'Sri Lanka': ('LKA', '144'),
    'St. Lucia': ('LCA', '662'),
    'St. Vincent and the Grenadines': ('VCT', '670'),
    'Sudan': ('SDN', '729'),
    'Suriname': ('SUR', '740'),
    'Swaziland': ('SWZ', '748'),
    'Sweden': ('SWE', '752'),
    'Switzerland': ('CHE', '756'),
    'Syria': ('SYR', '760'),
    'Tajikistan': ('TJK', '762'),
    'Tanzania': ('TZA', '834'),
    'Thailand': ('THA', '764'),
    'Timor-Leste': ('TLS', '626'),
    'Togo': ('TGO', '768'),
    'Tonga': ('TON', '776'),
    'Trinidad and Tobago': ('TTO', '780'),
    'Tunisia': ('TUN', '788'),
    'Turkey': ('TUR', '792'),
    'Turkmenistan': ('TKM', '795'),
    'Uganda': ('UGA', '800'),
    'Ukraine': ('UKR', '804'),
    'United Arab Emirates': ('ARE', '784'),
    'United Kingdom': ('GBR', '826'),
    'United States': ('USA', '840'),
    'Uruguay': ('URY', '858'),
    'Uzbekistan': ('UZB', '860'),
    'Vanuatu': ('VUT', '548'),
    'Venezuela': ('VEN', '862'),
    'Vietnam': ('VNM', '704'),
    'West Bank and Gaza': ('PSE', '275'),
    'Yemen': ('YEM', '887'),
    'Zambia': ('ZMB', '894'),
    'Zimbabwe': ('ZWE', '716'),
}
